import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import db from '../lib/db'

interface Todo {
  ID: string,
  Name: string
  Hint: string
}

interface Props {
    todos: Todo[]
}

const Home = ({todos}: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My TODO List
        </h1>
      <div>{todos.map((todo: any) => (
        <div className="card"><p>
         {todo.Name}
        </p></div>)) }</div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {

  const todos = await new Promise<Todo[]>((resolve, reject) => {
    db.all("SELECT * FROM demo", function(err:any, res:any){
      if(res) {
        resolve(res);
      }
      if(err) {
        reject(err)
      }
    })
  });
  return {
    props: {
      todos
    },
  }
} 

export default Home
